gantt
    title Trek Availability Timeline
    dateFormat  MM
    axisFormat %b
    tickInterval 1month

    section Year-Round Treks
    Kilimanjaro Peak Trek Expedition : 01, 12
    Chopta Chandrashila Tungnath Trek : 01, 12
    Sandakphu Trek : 01, 12
    Dayara Bugyal Trek : 01, 12
    Nag Tibba Weekend Trek : 01, 12

    section 11-Month Treks
    Brahmatal Trek : 01, 11
    Kedarkantha Trek : 01, 11

    section 10-Month Treks
    Deoban Weekend Trek : 01, 10
    Binsar Weekend Trek : 01, 10
    Bagji Bugyal Trek : 01, 10

    section 9-Month Treks
    Har Ki Doon Trek : 03, 11
    Goechala Trek : 03, 11
    Ranthan Kharak Trek : 03, 11
    Panwali Kantha Trek : 03, 11
    Ali Bedni Bugyal Trek : 03, 11
    Kareri Lake Trek : 03, 11

    section 8-Month Treks
    Annapurna Base Camp Trek : 03, 10
    Everest Base Camp Trek : 03, 10
    Gaumukh Tapovan Trek : 03, 10
    Adi Kailash and Om Parvat : 03, 10
    Bali Pass Trek : 03, 10
    Buran Ghati Trek : 03, 10
    Phulara Ridge Trek : 03, 10
    Mera Peak Expedition : 03, 10
    Panchkedar Trek & Drive : 03, 10
    Satopanth Lake Trek : 03, 10
    Dodital Darwa Pass Trek : 03, 10
    Black Peak Expedition : 03, 10
    Auden's Col Expedition : 03, 10
    Bagini Glacier & Changbang Base Camp : 03, 10
    Yunam Peak Trek Expedition : 03, 10
    Rudragaira Peak Expedition : 03, 10
    Roopkund Trek : 03, 10
    Pindari Glacier Trek : 03, 10
    Winter Kuari Pass Trek : 04, 11

    section 7-Month Treks
    Kedar Tal Trek : 04, 10

    section 6-Month Treks
    Rupin Pass Trek : 04, 09
    Nag Tibba Trek with Rafting : 04, 09
    Valley of Flowers Trek : 06, 11

    section 4-Month Treks
    Hampta Pass Trek : 07, 10
    Bhrigu Lake Trek : 07, 10
    Deo Tibba Peak Expedition : 07, 10
    Nafran Valley Trek : 07, 10
    Twin Peak - Kang Yatse II, Dzo Jongo, Markha Valley Trek : 07, 10
    Doodhpathri Trek : 07, 10
    Tarsar Marsar Trek : 07, 10
    Stok Kangri Peak Trek Expedition : 07, 10
    Pin Parvati Pass Trek : 07, 10
    Pin Bhaba Pass Trek : 07, 10
    Markha Valley Trek : 07, 10
    Kashmir Great Lakes Trek : 07, 10
    Kang Yatse II Peak Trek Expedition : 07, 10
    Kanamo Peak Trek Expedition : 07, 10
    Friendship Peak Expedition : 07, 10
    Dzo Jongo Peak Trek Expedition : 07, 10

    section 2-Month Treks
    Leh Ladakh Multi-Sports Trip : 08, 09
    Manali To Leh (Khardungla) Cycling Expedition : 08, 09
    Yoga & Meditation Retreat In The Himalayas : 09, 10
    Chadar Trek Frozen River : 12, 01

    section 1-Month Treks
    Sar Pass Trek : 04, 04
    Pir Ki Gali / Girjan Valley Trek : 05, 05
